site_name: Deep Learning pickers

nav:
    - Home: 'index.md'
    - Datasets:
        - El Hierro: 'datasets/hierro.md'
        - CASTOR: 'datasets/castor.md'
        - Maupasacq: 'datasets/maupasacq.md'
    - Pickers:
        - FilterPicker: 'pickers/filterpicker.md'
        - GPD: 'pickers/gpd.md'
        - PhaseNet: 'pickers/phasenet.md'
        - EQTransformer: 'pickers/eqtransformer.md'
        - PickNet: 'pickers/picknet.md'
    - Comparison: 
        - Metrics: 'metrics.md'
        - Results: 'results.md'
    - About: 'about.md'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
